---
- hosts: experiments
  remote_user: root
  tasks:

  - name: Install nginx package
    apt: name=nginx update_cache=yes
    sudo: yes

  - name: Starting nginx service
    service: name=nginx state=started
    sudo: yes

  - name: Debug
    debug: msg={{ ansible_distribution }}
